name: ftpconnect
description: Flutter simple and robust dart FTP Connect Library to interact with FTP Servers with possibility of zip and unzip files.
version: 0.1.9
#author: Salim Lachdhaf
homepage: https://github.com/salim-lachdhaf
git: https://github.com/salim-lachdhaf/ftpConnect
repository: https://github.com/salim-lachdhaf/ftpConnect

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  archive: ^2.0.13
  path: ^1.7.0
  intl: ^0.16.1

dev_dependencies:
  coverage: ^0.14.2
  test: ^1.15.7